%YAML:1.0

speed_skew: 5
imu_freqency : 250
acc_T_calibr: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.00611,-0.00130352,-0.00310935,0.0177334,
          0.00130701,1.00342,-0.0024619,0.0223509,
          0.00314038,0.00247981,0.996171,-0.209035,
          0., 0., 0., 1. ]


odom_freqency: 250
odom_baseline: 0.209



opt_T_odom: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.983945902559416,-0.024543804521931,0.101,
          0.024543804521931,0.983945902559416,-0.087,
          0. , 0. , 1.]
opt_freqency: 250
opt_iqThr: 1300
opt_iqTime: 0.1
data_path: "/Users/kongdaqing/Desktop/workspace/project/SLAM/DataSet/anker/b14-f2-13x3-r1/data_set/"
#data_path: "/Users/kongdaqing/Desktop/workspace/project/SLAM/DataSet/anker/b14-f2-20x5-r2/data_set/"
#data_path: "/media/zx/work/SlamDatas/anker/dataset/b14-f2-13x4-r1/"
#data_path: "/home/zx/workspace/Anker_Project/SweeperReckoning/data/anker/4/"
#data_path: "/media/zx/work/SlamDatas/anker/dataset/building14-floor2-12x4-collision/"
#data_path: "/media/zx/work/SlamDatas/anker/dataset/building14-floor2-movearound-collision/"
#data_path: "/media/zx/work/SlamDatas/anker/dataset/building14-floor2-circle1.2/"
#data_path: "/media/zx/work/SlamDatas/anker/dataset/building14-floor2-12x4/"
#data_path: "/media/zx/work/SlamDatas/anker/dataset/building14-floor1-4x3-noimage/"
detect_count: 10
detect_thr: 0.005
