%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1
num_of_cam: 2  

imu_topic: "/imu"
image0_topic: "/leftImg"
image1_topic: "/rightImg"
output_path: "/home/zx/workspace/SlamCodes/OpenSource/vinsFusion_ws/src/Vins-Fusion/output/640/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.


acc_T_calibr: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.00611,-0.00130352,-0.00310935,0.0177334,
          0.00130701,1.00342,-0.0024619,0.0223509,
          0.00314038,0.00247981,0.996171,-0.209035,
          0., 0., 0., 1. ]


body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.00665184,0.286804,0.957966, 0.00382701,
          -0.999967,-0.00257328,0.00771389,0.0456486,
          0.00467749,-0.957986,0.286778,0.0357241,
          0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.0151318,0.29744,0.95462,0.00466955,
          -0.999456,-0.023489,0.0231612,-0.024502,
           0.0293121,-0.954451,0.296923,0.0368016,
           0., 0., 0., 1. ]
#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 15                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8         # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/zx/workspace/SlamCodes/OpenSource/vinsFusion_office/src/VINS-Fusion/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0
loop_fusion_path: "/home/zx/workspace/SlamCodes/OpenSource/vinsFusion_ws/src/Vins-Fusion/loop_fusion/src/loop_fusion_package/loop_fusion_src/"
