%YAML:1.0


acc_T_calibr: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]
imu_freqency : 200

data_path: "/Users/kongdaqing/Desktop/workspace/project/SLAM/DataSet/euroc/MH_05/mav0/"
save_path: "/Users/kongdaqing/Desktop/workspace/project/SLAM/SweeperReckoning/output/"
